version: "3.7"

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:3.1.3
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
      - ${DATA_DIR}/node-red:/data
    networks:
      - pegasus

networks:
  pegasus:
    external: true

volumes:
  node-red:
    name: node-red
